---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  type: LoadBalancer
  ports:
  - name: hello-app-http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app